apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: "registryjjw5841.azurecr.io/tripinsights/user-java:1.0"
        env:
          - name: SQL_USER
            value: "sqladminqZq3023"
          - name: SQL_PASSWORD
            value: "hR1ug0Dd1"
          - name: SQL_SERVER
            value: "sqlserverqzq3023.database.windows.net"
          - name: SQL_DBNAME
            value: "mydrivingDB"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
  labels:
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: user-java
  selector:
    app: user-java
